### ISSUE TITLE
报错啊

### ISSUE THREAD

**Issue by jsjtwty** [yaodi962464/smzdm#2]
![BFC01BD2-0A72-400E-BE38-5AA5974E94A3](https://user-images.githubusercontent.com/40063335/76060255-ccef9d80-5fbb-11ea-9bce-0d232706ef21.png)

**Comment by yaodi962464** [comment]
@jsjtwty 已添加，我是在pycharm启动，所以目录有问题，你要在zhangdama目录下创建 Image目录
